/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import PubModelLandlord.LandLord;
import PubModelLandlord.LandlordFactory;
import java.awt.event.ActionListener;

/**
 *
 * @author dhirst1
 */
public class PubGui extends javax.swing.JFrame {

    /**
     * Creates new form PubGui
     */
    public PubGui() {
        initComponents();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSteps = new javax.swing.JTextField();
        txtDrinkInput = new javax.swing.JTextField();
        btnGetDrink = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSteps.setToolTipText("");
        txtSteps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStepsActionPerformed(evt);
            }
        });

        btnGetDrink.setText("Get drink");
        btnGetDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDrinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDrinkInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGetDrink))
                    .addComponent(txtSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDrinkInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetDrink))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStepsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStepsActionPerformed

    private void btnGetDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDrinkActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_btnGetDrinkActionPerformed

    public void setTextSteps(String steps){
        txtSteps.setText(steps);
    }
    public String getTextSteps(){
        return txtSteps.getText();
    }
    public String getDrinkInput(){
        return txtDrinkInput.getText();
    }
    public void setDrinkInput(String drinkInput){
        txtDrinkInput.setText(drinkInput);
    }
    public void setButtonListener(ActionListener e){
        btnGetDrink.addActionListener(e);
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetDrink;
    private javax.swing.JTextField txtDrinkInput;
    private javax.swing.JTextField txtSteps;
    // End of variables declaration//GEN-END:variables
}
